### ISSUE TITLE
Update for new version of Pandora?

### ISSUE THREAD

**Issue by bdwilson** [va2ron1/PanPlus#5]
Doesn't seem to work with newer versions of pandora. Works ok with 7.2.1, but that version doesn't support Apple Watch.  Thanks!

**Comment by va2ron1** [comment]
Check now version 1.2!

**Comment by bdwilson** [comment]
Thanks!  Just tried and wasn't successful with 7.8.  ppsideloader hasn't changed, so the only thing I did was update modify_app and copy the new 7.8 ipa to app.ipa.  7.8 opens and immediately closes; it does this several times then I get this error:

![image](https://cloud.githubusercontent.com/assets/317946/20269774/9fd5fd7a-aa52-11e6-834e-0fb17e7b1d29.png)

The old version of the app.ipa still works with version 1.2, however.

**Comment by va2ron1** [comment]
Are you using the right app? Remember the ipa directly from the AppStore doesn't works.

**Comment by bdwilson** [comment]
You're right.  That's what I was missing.  Apologies for not remembering that step :)  Thanks again for your time and efforts on this!

**Comment by bdwilson** [comment]
Should unlimited skips still work? They aren't after the update.
